from Tkinter import *
root=Tk()
root.title("My Information")
root.geometry("1100x1000")
Label(root,text="Project Title :PhoneBook",font='Arial 25').grid(row=0,column=0)
Label(root,text="Project of Python and database",font='Arial 25').grid(row=1,column=1)
Label(root,text="Developed By: Devik Sanghvi(181B081)",font='Arial 25 ',fg='blue').grid(row=2,column=1)
Label(root,text="Email: Porwalsahebdevik@gmail.com",font='Arial 25 ',fg='blue').grid(row=3,column=1)
Label(root,text="Contact No.: 9926827136",font='Arial 25 ',fg='blue').grid(row=4,column=1)
Label(root,text="------------------------------",font='Arial 25',fg='blue').grid(row=5,column=1)
Label(root,text="Project Guide: Dr.Mahesh Kumar",font='Arial 25 ',fg='Black').grid(row=6,column=1)
Label(root,text="------------------------------",font='Arial 25',fg='blue').grid(row=7,column=1)
Label(root,text="make mouse movement over this screen to close",font='Arial 25',fg='red').grid(row=8,column=1)
##a=PhotoImage(file="image2.gif")
##Label(root,image=a).grid(row=4,column=1)
def devik(z=1):
    root.destroy()
root.bind('<Motion>',devik)
mainloop()
